export const APPOINTMENTS_MONTH_FETCH_START = 'APPOINTMENTS_MONTH_FETCH_START';
export const APPOINTMENTS_MONTH_FETCH_FAIL = 'APPOINTMENTS_MONTH_FETCH_FAIL';
export const APPOINTMENTS_MONTH_FETCHED = 'APPOINTMENTS_MONTH_FETCHED';

export const SURGERY_MONTH_FETCH_START = 'SURGERY_MONTH_FETCH_START';
export const SURGERY_MONTH_FETCH_FAIL = 'SURGERY_MONTH_FETCH_FAIL';
export const SURGERY_MONTH_FETCHED = 'SURGERY_MONTH_FETCHED';

export const APPOINTMENTS_PAST_MONTHS_FETCH_START = 'APPOINTMENTS_PAST_MONTHS_FETCH_START';
export const APPOINTMENTS_PAST_MONTHS_FETCH_FAIL = 'APPOINTMENTS_PAST_MONTHS_FETCH_FAIL';
export const APPOINTMENTS_PAST_MONTHS_FETCHED = 'APPOINTMENTS_PAST_MONTHS_FETCHED';

export const SURGERIES_PAST_MONTHS_FETCH_START = 'SURGERIES_PAST_MONTHS_FETCH_START';
export const SURGERIES_PAST_MONTHS_FETCH_FAIL = 'SURGERIES_PAST_MONTHS_FETCH_FAIL';
export const SURGERIES_PAST_MONTHS_FETCHED = 'SURGERIES_PAST_MONTHS_FETCHED';

export const NPS_FETCH_START = 'NPS_FETCH_START';
export const NPS_FETCH_FAIL = 'NPS_FETCH_FAIL';
export const NPS_FETCHED = 'NPS_FETCHED';